# Generated by Django 3.2 on 2021-06-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_berkas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkas',
            name='acara',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='konsumsi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='perlengkapan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
