# Generated by Django 3.2 on 2021-06-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_berkas_berkas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkas',
            name='waktu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
