# Generated by Django 3.2 on 2021-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_berkas_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=200, null=True)),
                ('isi', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
