# Generated by Django 3.2 on 2021-06-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_berita_isi'),
    ]

    operations = [
        migrations.CreateModel(
            name='proker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namamenteri', models.CharField(blank=True, max_length=200, null=True)),
                ('prokernya', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabinet', models.CharField(blank=True, max_length=200, null=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('filesk', models.FileField(blank=True, null=True, upload_to='')),
                ('fileproker', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='berkas',
            old_name='berkas',
            new_name='file',
        ),
        migrations.AddField(
            model_name='berkas',
            name='relasiproker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.proker'),
        ),
    ]
