# Generated by Django 3.2 on 2021-06-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_berkas_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengunggah', models.CharField(blank=True, max_length=200, null=True)),
                ('kegiatan', models.CharField(blank=True, max_length=200, null=True)),
                ('waktu', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('acara', models.IntegerField(blank=True, null=True)),
                ('konsumsi', models.IntegerField(blank=True, null=True)),
                ('perlengkapan', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('relasiproker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.proker')),
            ],
        ),
    ]
