# Generated by Django 3.2 on 2021-06-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_laporan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='acara',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='file',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='kegiatan',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='konsumsi',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='perlengkapan',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='relasiproker',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='waktu',
        ),
        migrations.AddField(
            model_name='laporan',
            name='relasiproposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.berkas'),
        ),
    ]
