# Generated by Django 3.2 on 2021-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_laporan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='konsumsi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='perlengkapan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
