# Generated by Django 3.2 on 2021-07-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20210701_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='acara',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
