# Generated by Django 3.2 on 2021-07-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_laporan_acara'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laporan',
            new_name='tabellaporan',
        ),
    ]
