# Generated by Django 3.2 on 2021-07-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_rename_laporan_tabellaporan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berkas',
            name='kegiatan',
        ),
    ]
