# Generated by Django 3.2 on 2021-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_bemf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemf',
            name='category',
            field=models.CharField(blank=True, choices=[('BEM Fakultas teknik', 'BEM Fakultas agama islam')], max_length=200, null=True),
        ),
    ]
