# Generated by Django 3.2 on 2021-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_bemf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemf',
            name='category',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door'), ('Out Door', 'Out Door')], max_length=200, null=True),
        ),
    ]
