# Generated by Django 3.2 on 2021-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_remove_berkas_waktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
