# Generated by Django 3.2 on 2021-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20210713_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellaporan',
            name='catatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabellaporan',
            name='notifikasi',
            field=models.CharField(blank=True, choices=[('diterima', 'diterima'), ('ditolak', 'ditolak')], max_length=200, null=True),
        ),
    ]
