# Generated by Django 3.2 on 2021-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20210716_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellaporan',
            name='notifikasi',
            field=models.CharField(blank=True, choices=[('diterima', 'diterima'), ('ditolak', 'ditolak')], max_length=200, null='belum diperiksa'),
        ),
    ]
