# Generated by Django 3.2 on 2021-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_tabellaporan_notifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellaporan',
            name='notifikasi',
            field=models.CharField(blank=True, choices=[('diterima', 'diterima'), ('ditolak', 'ditolak')], max_length=200, null=True),
        ),
    ]
