# Generated by Django 3.2 on 2021-07-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_alter_tabellaporan_notifikasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bemf',
        ),
        migrations.DeleteModel(
            name='bemu',
        ),
        migrations.DeleteModel(
            name='kemahasiswaan',
        ),
    ]
