# Generated by Django 3.2 on 2021-07-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20210717_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sk',
        ),
    ]
