# Generated by Django 3.2 on 2021-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_tabelproposal_bem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellaporan',
            name='bem',
            field=models.CharField(blank=True, choices=[('BEM-UNUJA', 'BEM-UNUJA'), ('BEMF-teknik', 'BEMF-teknik'), ('BEMF-FAI', 'BEMF-FAI'), ('BEMF-KES', 'BEMF-KES'), ('BEMF-Soshum', 'BEMF-Soshum')], max_length=200, null=True),
        ),
    ]
