# Generated by Django 3.2 on 2021-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_tabellaporan_bem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellaporan',
            name='notifikasi',
            field=models.CharField(blank=True, choices=[('diterima', 'diterima'), ('ditolak', 'ditolak'), ('diperiksa', 'diperiksa')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tabelproposal',
            name='notifikasi',
            field=models.CharField(blank=True, choices=[('diterima', 'diterima'), ('ditolak', 'ditolak'), ('diperiksa', 'diperiksa')], max_length=200, null=True),
        ),
    ]
