# Generated by Django 3.2 on 2021-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_auto_20210717_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proker',
            old_name='namamenteri',
            new_name='devisi',
        ),
        migrations.RenameField(
            model_name='proker',
            old_name='prokernya',
            new_name='namakegiatan',
        ),
        migrations.AddField(
            model_name='proker',
            name='bem',
            field=models.CharField(blank=True, choices=[('BEM-UNUJA', 'BEM-UNUJA'), ('BEMF-teknik', 'BEMF-teknik'), ('BEMF-FAI', 'BEMF-FAI'), ('BEMF-KES', 'BEMF-KES'), ('BEMF-Soshum', 'BEMF-Soshum')], max_length=200, null=True),
        ),
    ]
