# Generated by Django 3.2 on 2021-07-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20210724_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabellaporan',
            name='bem',
        ),
    ]
