# Generated by Django 3.2 on 2021-07-30 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0042_bem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bem',
            old_name='jenisbem',
            new_name='jenis_bem',
        ),
        migrations.CreateModel(
            name='Adminbem',
            fields=[
                ('id_Adminbem', models.AutoField(primary_key=True, serialize=False)),
                ('nama_anggota', models.CharField(max_length=200)),
                ('telp_anggota', models.CharField(max_length=100)),
                ('id_Bem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.bem')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adminbem',
            },
        ),
    ]
