# Generated by Django 3.2 on 2021-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20210730_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbem',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
