# Generated by Django 3.2 on 2021-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_adminbem_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='jenis_bem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
