# Generated by Django 3.2 on 2021-07-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_auto_20210730_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='bem',
            field=models.CharField(blank=True, choices=[('BEM-UNUJA', 'BEM-UNUJA'), ('BEMF-teknik', 'BEMF-teknik'), ('BEMF-FAI', 'BEMF-FAI'), ('BEMF-KES', 'BEMF-KES'), ('BEMF-Soshum', 'BEMF-Soshum')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='berita',
            name='pengunggah',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
