# Generated by Django 3.2 on 2021-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20210730_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='coba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
