# Generated by Django 3.2 on 2021-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_coba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbem',
            name='id_Bem',
        ),
        migrations.AddField(
            model_name='adminbem',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminbem',
            name='jenis_bem',
            field=models.CharField(blank=True, choices=[('BEM-UNUJA', 'BEM-UNUJA'), ('BEMF-teknik', 'BEMF-teknik'), ('BEMF-FAI', 'BEMF-FAI'), ('BEMF-KES', 'BEMF-KES'), ('BEMF-Soshum', 'BEMF-Soshum')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Bem',
        ),
    ]
