# Generated by Django 3.2 on 2021-08-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20210801_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelproposal',
            name='id_Adminbem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.adminbem'),
        ),
    ]
