# Generated by Django 3.2 on 2021-08-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_tabelproposal_id_adminbem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelproposal',
            name='bem',
        ),
    ]
