# Generated by Django 3.2 on 2021-08-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_remove_tabelproposal_bem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelproposal',
            name='pengunggah',
        ),
    ]
