# Generated by Django 3.2 on 2021-08-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_remove_proker_bem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proker',
            name='sifatkegiatan',
            field=models.CharField(blank=True, choices=[('mingguan', 'mingguan'), ('bulanan', 'bulanan'), ('tahunan', 'tahunan')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proker',
            name='targetkegiatankegiatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proker',
            name='tujuankegiatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proker',
            name='waktukegiatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
