# Generated by Django 3.2 on 2021-08-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_auto_20210802_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proker',
            old_name='namakegiatan',
            new_name='nama_kegiatan',
        ),
        migrations.RenameField(
            model_name='proker',
            old_name='sifatkegiatan',
            new_name='sifat_kegiatan',
        ),
        migrations.RenameField(
            model_name='proker',
            old_name='targetkegiatankegiatan',
            new_name='target_kegiatan',
        ),
        migrations.RenameField(
            model_name='proker',
            old_name='tujuankegiatan',
            new_name='tujuan_kegiatan',
        ),
        migrations.RenameField(
            model_name='proker',
            old_name='waktukegiatan',
            new_name='waktu_kegiatan',
        ),
    ]
