# Generated by Django 3.2 on 2021-08-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_auto_20210802_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='proker',
            name='catatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proker',
            name='proposal_kegiatan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proker',
            name='tanggapan_proker',
            field=models.CharField(blank=True, choices=[('masih diperika', 'masih diperika'), ('DITERIMA', 'DITERIMA'), ('DITOLAK', 'DITOLAK')], max_length=200, null=True),
        ),
    ]
