# Generated by Django 3.2 on 2021-08-02 03:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_auto_20210802_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='proker',
            name='ringkasan_anggaran',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
