# Generated by Django 3.2 on 2021-08-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_proker_terbitan_sk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proker',
            name='tanggapan_proker',
            field=models.CharField(blank=True, choices=[('Dana belum cair', 'Dana belum cair'), ('Dana sudah cair', 'Dana sudah cair')], max_length=200, null=True),
        ),
    ]
