# Generated by Django 3.2 on 2021-08-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_alter_proker_tanggapan_proker'),
    ]

    operations = [
        migrations.AddField(
            model_name='proker',
            name='struktur_kepanitiaan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proker',
            name='tanggapan_proker',
            field=models.CharField(blank=True, choices=[('Dana BELUM CAIR', 'Dana BELUM CAIR'), ('Dana SUDAH CAIR', 'Dana SUDAH CAIR')], max_length=200, null=True),
        ),
    ]
