# Generated by Django 3.2 on 2021-08-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_auto_20210802_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='proker',
            name='pencairan_proker',
            field=models.CharField(blank=True, choices=[('Dana BELUM CAIR', 'Dana BELUM CAIR'), ('Dana SUDAH CAIR', 'Dana SUDAH CAIR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proker',
            name='tanggapan_proker',
            field=models.CharField(blank=True, choices=[('masih diperika', 'masih diperika'), ('DITERIMA', 'DITERIMA'), ('DITOLAK', 'DITOLAK')], max_length=200, null=True),
        ),
    ]
