# Generated by Django 3.2 on 2021-08-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_auto_20210802_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proker',
            options={},
        ),
    ]
