# Generated by Django 3.2 on 2021-08-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_alter_proker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proker',
            options={'verbose_name_plural': 'proker'},
        ),
    ]
