# Generated by Django 3.2 on 2021-08-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_berita_id_adminbem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'berita'},
        ),
        migrations.RemoveField(
            model_name='berita',
            name='bem',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='pengunggah',
        ),
    ]
