# Generated by Django 3.2 on 2021-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_auto_20210802_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, default='logo.png', upload_to=''),
        ),
    ]
