# Generated by Django 3.2 on 2021-08-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_alter_berita_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proker',
            name='proposal_kegiatan',
            field=models.FileField(blank=True, default='logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proker',
            name='struktur_kepanitiaan',
            field=models.FileField(blank=True, default='logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proker',
            name='terbitan_sk',
            field=models.FileField(blank=True, default='logo.png', upload_to=''),
        ),
    ]
