# Generated by Django 3.2 on 2021-08-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_auto_20210803_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proker',
            name='catatan',
            field=models.CharField(blank=True, default='tidak ada catatan', max_length=200),
        ),
        migrations.AlterField(
            model_name='proker',
            name='pencairan_proker',
            field=models.CharField(blank=True, choices=[('Dana BELUM CAIR', 'Dana BELUM CAIR'), ('Dana SUDAH CAIR', 'Dana SUDAH CAIR')], default='belum ditanggapi', max_length=200),
        ),
        migrations.AlterField(
            model_name='proker',
            name='tanggapan_proker',
            field=models.CharField(blank=True, choices=[('masih diperika', 'masih diperika'), ('DITERIMA', 'DITERIMA'), ('DITOLAK', 'DITOLAK')], default='belum diperiksa', max_length=200),
        ),
    ]
