# Generated by Django 3.2 on 2021-08-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0074_alter_adminbem_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, default='erorgambar.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proker',
            name='proposal_kegiatan',
            field=models.FileField(blank=True, default='erorfile.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proker',
            name='struktur_kepanitiaan',
            field=models.FileField(blank=True, default='erorfile.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proker',
            name='terbitan_sk',
            field=models.FileField(blank=True, default='erorfile.jpg', upload_to=''),
        ),
    ]
