# Generated by Django 3.2 on 2021-08-03 07:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_auto_20210803_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabellaporan',
            name='acara',
        ),
        migrations.RemoveField(
            model_name='tabellaporan',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='tabellaporan',
            name='konsumsi',
        ),
        migrations.RemoveField(
            model_name='tabellaporan',
            name='notifikasi',
        ),
        migrations.RemoveField(
            model_name='tabellaporan',
            name='pengunggah',
        ),
        migrations.RemoveField(
            model_name='tabellaporan',
            name='perlengkapan',
        ),
        migrations.RemoveField(
            model_name='tabellaporan',
            name='relasiproposal',
        ),
        migrations.AddField(
            model_name='tabellaporan',
            name='anggaran_dana',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabellaporan',
            name='id_Adminbem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.adminbem'),
        ),
        migrations.AddField(
            model_name='tabellaporan',
            name='id_berita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.berita'),
        ),
        migrations.AddField(
            model_name='tabellaporan',
            name='id_proker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.proker'),
        ),
        migrations.AddField(
            model_name='tabellaporan',
            name='tanggapan_laporan',
            field=models.CharField(blank=True, choices=[('masih diperika', 'masih diperika'), ('DITERIMA', 'DITERIMA'), ('DITOLAK', 'DITOLAK')], default='belum diperiksa', max_length=200),
        ),
        migrations.AlterField(
            model_name='tabellaporan',
            name='catatan',
            field=models.CharField(blank=True, default='tidak ada catatan', max_length=200),
        ),
        migrations.AlterField(
            model_name='tabellaporan',
            name='file',
            field=models.FileField(blank=True, default='erorfile.jpg', upload_to=''),
        ),
    ]
