# Generated by Django 3.2 on 2021-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_alter_tabellaporan_tanggapan_laporan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proker',
            name='pencairan_proker',
            field=models.CharField(blank=True, choices=[('Dana BELUM CAIR', 'Dana BELUM CAIR'), ('Dana SUDAH CAIR', 'Dana SUDAH CAIR')], default='erorfile.jpg', max_length=200),
        ),
    ]
