# Generated by Django 3.2 on 2021-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_alter_proker_waktu_kegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proker',
            name='waktu_kegiatan',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
