# Generated by Django 3.2 on 2021-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_alter_adminbem_telp_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proker',
            name='pencairan_proker',
            field=models.CharField(blank=True, choices=[('Dana BELUM CAIR', 'Dana BELUM CAIR'), ('Dana SUDAH CAIR', 'Dana SUDAH CAIR')], default='belum diputuskan', max_length=200),
        ),
    ]
