# Generated by Django 3.2 on 2021-08-08 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_alter_proker_pencairan_proker'),
    ]

    operations = [
        migrations.CreateModel(
            name='sk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat_permohonansk', models.FileField(blank=True, default='erorfile.jpg', upload_to='')),
                ('program_kerja', models.FileField(blank=True, default='erorfile.jpg', upload_to='')),
                ('rab', models.FileField(blank=True, default='erorfile.jpg', upload_to='')),
                ('total_rab', models.IntegerField(blank=True, null=True)),
                ('tanggapan_sk', models.CharField(blank=True, choices=[('masih diperika', 'masih diperika'), ('DITERIMA', 'DITERIMA'), ('DITOLAK', 'DITOLAK')], default='belum diperiksa', max_length=200)),
                ('catatan', models.CharField(blank=True, default='tidak ada catatan', max_length=200)),
                ('terbitan_sk', models.FileField(blank=True, default='erorfile.jpg', upload_to='')),
                ('id_Adminbem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.adminbem')),
            ],
            options={
                'verbose_name_plural': 'sk',
            },
        ),
    ]
