# Generated by Django 3.2 on 2021-08-08 01:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0089_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sk',
            name='struktur_anggota',
            field=models.FileField(blank=True, default='erorfile.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='sk',
            name='visi_misi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
