# Generated by Django 3.2 on 2021-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_auto_20210808_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proker',
            name='ringkasan_anggaran',
            field=models.IntegerField(blank=True, default='628'),
        ),
        migrations.AlterField(
            model_name='tabellaporan',
            name='anggaran_dana',
            field=models.IntegerField(blank=True, default='628'),
        ),
    ]
