# Generated by Django 3.2 on 2021-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_auto_20210808_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellaporan',
            name='anggaran_dana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
