# Generated by Django 3.2 on 2021-08-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0092_alter_tabellaporan_anggaran_dana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbem',
            name='jenis_bem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proker',
            name='ringkasan_anggaran',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
