# Generated by Django 3.2 on 2021-08-10 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0095_proker_relasi_proker'),
    ]

    operations = [
        migrations.AddField(
            model_name='coba',
            name='id_Adminbem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.adminbem'),
        ),
    ]
