# Generated by Django 3.2 on 2021-08-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0096_coba_id_adminbem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coba',
            name='img',
            field=models.ImageField(blank=True, default='erorfile.jpg', upload_to=''),
        ),
    ]
