# Generated by Django 3.2 on 2021-08-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0097_alter_coba_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbem',
            name='foto_profil',
        ),
        migrations.RemoveField(
            model_name='adminbem',
            name='nama_anggota',
        ),
    ]
