# Generated by Django 3.2 on 2021-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0098_auto_20210813_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbem',
            name='jenis_bem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
