# Generated by Django 3.2 on 2021-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_alter_adminbem_jenis_bem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sk',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
