# Generated by Django 3.2 on 2021-08-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0101_alter_sk_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sk',
            name='date_created',
        ),
    ]
