# Generated by Django 3.2 on 2021-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0102_remove_sk_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_periode', models.CharField(blank=True, default='2020-2021', max_length=9)),
            ],
            options={
                'verbose_name_plural': 'periode',
            },
        ),
    ]
