# Generated by Django 3.2 on 2021-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0103_periode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='periode',
        ),
    ]
