# Generated by Django 3.2 on 2021-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0104_delete_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sk',
            name='periode',
            field=models.CharField(blank=True, default='2020-2021', max_length=9),
        ),
    ]
